[build]
  command = "pip install -r requirements.txt"
  publish = "static"
  functions = "api"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/*"
  to = "/api/index"
  status = 200
